### ISSUE TITLE
Assert error in vcc_func(), vcc_expr.c line 608:   Condition((rfmt) != 0) not true.

### ISSUE THREAD

**Issue by SantoDE** [carlosabalde/libvmod-cfg#10]
Hey there,

I'm trying that vmod in my current setup. However, I'm having a problem with varnishd in version "varnishd (varnish-5.2.1 revision 67e562482)".

```vcl 4.0;

import std;
import cfg;

sub vcl_init {
    new env = cfg.env();

    if (env.is_set("INCLUDE_VCL_CONFIG")) {
        new config = env.get("INCLUDE_VCL_CONFIG");
    }
}
```

ends in:
`Error:
Message from VCC-compiler:
Assert error in vcc_func(), vcc_expr.c line 608:
  Condition((rfmt) != 0) not true.
Running VCC-compiler failed, signal 6
VCL compilation failed
`
Anyone has an idea? :)

**Comment by carlosabalde** [comment]
You have an syntax error in the snippet. I guess what you want to do is ``new config = cfg.file(env.get("INCLUDE_VCL_CONFIG"));``.

**Comment by SantoDE** [comment]
Hey. I dont really want to load a whole file. I just want the string behind the env var. So cfg.file would be too much I guess?

Thanks for the help!

**Comment by carlosabalde** [comment]
If I understood correctly you just want to be able to access to the value of ``$INCLUDE_VCL_CONFIG``. If so, it's ok read the value using ``env.get("INCLUDE_VCL_CONFIG")``, but you cannot assign it to ``new config``.  That's simply invalid VCL syntax.

**Comment by SantoDE** [comment]
Ah, so getting just the value would work? Thats cool! One more question:

Can I use this to e.g. have a "variable" include? Or to set ports for a backend or something? Or where is this limited?

**Comment by carlosabalde** [comment]
You could use it only inside VCL subroutines: ``vcl_init``, ``vcl_recv``, etc.

**Comment by SantoDE** [comment]
Alright. Thanks a lot! :)
