### ISSUE TITLE
Adding modules to JS scripts?

### ISSUE THREAD

**Issue by LMalikov** [carlosabalde/libvmod-cfg#31]
Is it possible to add Node modules (i.e. `require`) to the JS script? Couldn't find any examples here, but I think Duktape has a way to do that?

PS: I'm trying to add RSA encryption to my VCL and it looks like the only way to do so is through a JS script and crypto module.
PSS: Sorry, it's me again :) Thanks in advance!

**Comment by carlosabalde** [comment]
I'm sorry, but not planning to do that in the near future. In addition, doing such a thing using JavaScript or Lua would be a terrible idea from a performance point of view. An ad-hoc VMOD for encryption would be the only reasonable way to go.
