### ISSUE TITLE
Failed to parse remote

### ISSUE THREAD

**Issue by amoghyermalkar123** [carlosabalde/libvmod-cfg#32]
```
sub vcl_init {
        new env = cfg.env();

        if (env.is_set("VCL_SETTINGS")) {
                new settings = cfg.file(env.get("VCL_SETTINGS"));
        }

        new settings_two = cfg.file("http://127.0.0.1:2015/config.json");
}
```

settings is where i try to read and parse a local json file and settings_two is where i read and parse a remote json file.

Both of these operations fail with the same error:

```
[CFG][file_parse_ini:152] Failed to parse remote (file=settings, location=file:///etc/varnish/config.json, is_backup=0, format=ini,>

[CFG][file_parse_ini:152] Failed to parse remote (file=settings_two, location=http://127.0.0.1:2015/config.json, is_backup=0, ...
```
Why would this not be working?

My versions:
varnish : 6.2.1
cfg vmod : 6.2-archived

**Comment by amoghyermalkar123** [comment]
This is how I set VCL_SETTINGS Environment variable:

I edit the varnish.service file to have :

`Environment="VCL_SETTINGS=file:///etc/varnish/config.json"`

**Comment by carlosabalde** [comment]
You need to specify the format when reading the file: `format=json`.
