### ISSUE TITLE
tests fail for branch 6.6

### ISSUE THREAD

**Issue by amoghyermalkar123** [carlosabalde/libvmod-cfg#33]
```
FAIL: tests/VCL-temperature-and-discard.vtc
FAIL: tests/env.get.vtc
FAIL: tests/env.is-set.vtc
FAIL: tests/file.backup.vtc
FAIL: tests/file.dump.vtc
FAIL: tests/file.ini.get.vtc
FAIL: tests/file.ini.is-set.vtc
FAIL: tests/file.inspect.vtc
FAIL: tests/file.json.get.vtc
FAIL: tests/file.json.is-set.vtc
FAIL: tests/file.period.vtc
FAIL: tests/file.reload.vtc
FAIL: tests/file.remote.vtc
FAIL: tests/rules.get.vtc
FAIL: tests/rules.inspect.vtc
FAIL: tests/script.blocked-workers.vtc
FAIL: tests/script.inspect.vtc
FAIL: tests/script.javascript-basics-1.vtc
FAIL: tests/script.javascript-basics-2.vtc
FAIL: tests/script.lua-basics-1.vtc
FAIL: tests/script.lua-basics-2.vtc
FAIL: tests/script.regexps.vtc
=======================================
....
```

varnish version :
```
varnishd (varnish-6.6.1 revision e6a8c860944c4f6a7e1af9f40674ea78bbdcdc66)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2020 Varnish Software
```

cfg VMOD branch : `6.6`
lua version : `5.3.6`
lua jit version : `luaJIT-2.1.0-beta3`

this is my linux distro:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

* Any errors or warnings encountered while building anything from source ? 
None. All the building and installation completed successfully.

Q : Why do you think the tests fail here given the above context?

(please comment if you need any additional information to answer the posed question, thank you)

please help, @carlosabalde :)

**Comment by davidfb** [comment]
Hi! Do you have the tests logs in src/test-suite.log after doing make check? Could you share those contents in order to debug this issue? Thank you

**Comment by amoghyermalkar123** [comment]
@davidfb yes ofcourse. Since the contents are pretty huge, here is text file containing an entire log after a `make check` was ran,
[cfg_test_log.txt](https://github.com/carlosabalde/libvmod-cfg/files/6977022/cfg_test_log.txt)

**Comment by davidfb** [comment]
Hi, seems like the Varnish Cache instances spawn by the test process aren't able to access the compiled VMOD. Are you running the compilation and the tests as root? Cause that could be the problem, as Varnish Cache processes will drop privileges and run as a non-root user, and so they might not have access to the previously compiled object files.

Compilation, tests and installation of the cfg VMOD are meant to be done the standard way as for any other Varnish VMOD, so ideally, only `make install` should be run as root, or problems like this could arise.

Does this help?

**Comment by amoghyermalkar123** [comment]
To install the cfg vmod here are the steps I followed:
1) cd libvmod-cfg
2) git checkout 6.6
3) ./autogen.sh
4) ./configure
5) make
6) make check (this step fails)
7) sudo make install (this step also fails since checks failed)

> Are you running the compilation and the tests as root? 

By the looks of it, no.

> so ideally, only make install should be run as root, or problems like this could arise.

so it seems like I am doing exactly this.

I'll clean the repo and redo the installation again.

**Comment by amoghyermalkar123** [comment]
@davidfb cleaning out the repository (`git clean -f -x -d`) and following the same steps mentioned above helped. Interesting right?
Do you think it has something to do with uncleaned repos?

In any case, thank you for taking your time out for looking into this :)

**Comment by amoghyermalkar123** [comment]
@davidfb closing this

**Comment by amoghyermalkar123** [comment]
Sorry for reopening, but all was working fine for the last few hours until a few minutes ago.
I had made some changes to the VCL and hence went on to restart varnish.

But this time it says:
```
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2021-08-13 19:59:54 UTC; 2min 42s ago
  Process: 24986 ExecStart=/usr/sbin/varnishd -a :6081 -a localhost:8443,PROXY -p feature=+http2 -f /etc/varnish/default.vcl -s malloc,256m (code=exit

varnishd[24986]:         File name: /usr/lib/varnish/vmods/libvmod_cfg.so
varnishd[24986]:         dlerror: /lib/x86_64-linux-gnu/libvarnishapi.so.2: version `LIBVARNISHAPI_2.5' not found (re
varnishd[24986]: ('/etc/varnish/default.vcl' Line 3 Pos 8)
varnishd[24986]: import cfg;
varnishd[24986]: -------###-
varnishd[24986]: Running VCC-compiler failed, exited with 2
varnishd[24986]: VCL compilation failed
systemd[1]: varnish.service: Control process exited, code=exited, status=255/EXCEPTION
systemd[1]: varnish.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
```

It had successfully imported the cfg VMOD before. But running a restart on the service failed just a few hours later.

**Comment by amoghyermalkar123** [comment]
@davidfb it turns out the problem is a resultant of unclean installations of varnish.

The system that's now running varnish 6.6 had previously varnish 6.2.1 installed. Ofcourse I did purge the previous varnish before installng the new one but it seems some piece remained missing.
The same error is thrown when i run `sudo varnishlog`

Do you have any suggestions as to how I can solve this?

**Comment by davidfb** [comment]
Hi! Could it be that your Varnish Cache installation suffered an upgrade (or downgrade) that was waiting to be applied on the next restart? The VMOD can only run on the exact same version of Varnish that was used to compile it. If there's a mismatch, an error will be thrown and Varnish Cache won't start.

**Comment by amoghyermalkar123** [comment]
@davidfb you are correct. We did an upgrade on varnish on our system. We purged the previous varnish before doing so. 

The cause of the problem was apparently purging had not deleted an old symlink to a shared library. I had to manually delete it and rebuild everything.

This solved it.
