### ISSUE TITLE
about json format

### ISSUE THREAD

**Issue by redbox-cdn** [carlosabalde/libvmod-cfg#4]
Hi , is it possible to set the json format?
*I would like to use Json file in local or remote.

Best regards

**Comment by carlosabalde** [comment]
The VMOD is implemented in a way that adding support for alternative formats such as JSON should be simple. However at the moment only ini files are supported.

**Comment by redbox-cdn** [comment]
Hi Thank you for reply.

Additional question 
what is the maximum supported size of ini config file?
When I test of the  250Kb, the varnish is panic.

Error:
Assert error in cfg_dump(), vmod_cfg.c line 154:#012  Condition(free_ws > 0) not true.

*this issue related to varnish config..?

Best regards.

**Comment by carlosabalde** [comment]
The VMOD does not limit the file size. However, in order to read the ini file, parse contents, etc. the VMOD is limited by the memory available in the client and backend workspaces (i.e. `workspace_client` and `workspace_backend` varnishd parameters). Try to increase those values and try again.

**Comment by redbox-cdn** [comment]
Hi thank you for the quick reply
this issue has been solved. I added workspace_client and workspace_backend.

Thanks!

**Comment by carlosabalde** [comment]
FYI: I've just added (see https://github.com/carlosabalde/libvmod-cfg/commit/3ac1cbecc9f012d3238059bf8ab02ef6c3d17d29) limited JSON support to the VMOD.
