### ISSUE TITLE
Build failure (5 FAIL out of 9)

### ISSUE THREAD

**Issue by ldng** [carlosabalde/libvmod-cfg#5]
Hi,

the project compile fine but the tests are falling.

libvmod-cfg master
varnishd (varnish-4.1.5 revision 2c82b1c)

**Comment by carlosabalde** [comment]
From README.md:

> Beware this project contains multiples branches (master, 4.1, etc.). Please, select the branch to be used depending on your Varnish Cache version (Varnish trunk → master, Varnish 4.1.x → 4.1, etc.).

Please, try using the right branch.

**Comment by ldng** [comment]
Hum, right ! And I read it yesterday but forgot to do it !
Sorry about that. 
Thanks.

**Comment by carlosabalde** [comment]
You're welcome! Enjoy the VMOD 🎉
